apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  source:
    path: https://gitlab.com/as9081914/argo/-/blob/main/manifest.yam
    repoURL: git@gitlab.com:as9081914/argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null